services:
  client:
    image: foldingathome/fah-gpu-bastet:cuda-rocm
    build:
      context: .
      args:
        CUDA_RELEASE: "${CUDA_RELEASE:-11.7.1}"
        ROCM_RELEASE: "${ROCM_RELEASE:-6.4.4}"
      tags:
        - "foldingathome/fah-gpu-bastet:cuda${CUDA_RELEASE:-11.7.1}-rocm${ROCM_RELEASE:-6.4.4}"
        - "foldingathome/fah-gpu-bastet:${VERSION:-26.07.0}-cuda-rocm"
        - "foldingathome/fah-gpu-bastet:${VERSION:-26.07.0}-cuda${CUDA_RELEASE:-11.7.1}-rocm${ROCM_RELEASE:-6.4.4}"
    ports:
      - "7396:7396"
    # Options for nVidia CUDA
    gpus: all
    # Options for AMD ROCm
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    security_opt:
      - seccomp=unconfined
    group_add:
      - "video"
      - "${RENDER_GID:-render}"
    # Options for setting local directory
    # user: "1000:1000"
    # volumes:
    #  - "/etc/machine-id:/etc/machine-id:ro"
    #  - "${HOME}/fah:/fah"
