# Folding@home nVidia CUDA Container

# CUDA 11.7.1 is the lowest version of ubuntu22.04 jammy
ARG CUDA_RELEASE=11.7.1

FROM nvidia/cuda:${CUDA_RELEASE}-base-ubuntu22.04
LABEL description="Folding@home nVidia CUDA Container for Bastet"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      polkitd \
      python3 \
      python3-websocket \
      curl \
      clinfo \
    # setup OpenCL ICD for nVidia
    && mkdir -p /etc/OpenCL/vendors \
    && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd \
    # create libOpenCL.so instead of install ocl-icd-opencl-dev
    && ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/x86_64-linux-gnu/libOpenCL.so \
    # add users and groups to properly install fah-client.deb
    && useradd -ms /bin/bash fah-client \
    && groupadd -r render \
    && usermod -aG render,video fah-client \
    && mkdir /fah \
    && chown fah-client:fah-client /fah \
    # download and verify checksum
    && curl -fsSL \
      https://download.foldingathome.org/releases/public/fah-client/debian-10-64bit/release/fah-client_8.5.5_amd64.deb \
      -o fah-client.deb \
    && echo "4f9c8bed9b2893752afb87e2796512ca0ca300ffc3d6035c518d56360370886c fah-client.deb" \
      | sha256sum -c --strict - \
    # install and cleanup
    && DEBIAN_FRONTEND=noninteractive dpkg --install --force-depends fah-client.deb \
    && rm -rf fah-client.deb \
    && apt-get purge --autoremove -y curl \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

USER fah-client
WORKDIR "/fah"
VOLUME ["/fah"]
EXPOSE 7396

# allow access outside container (allow option accepts just one entry)
ENTRYPOINT ["fah-client", "--allow", "0/0", "--http-addresses", "0.0.0.0:7396"]
