# Folding@home AMD ROCm Container

# To reduce the image size, install the minimal packages for OpenCL
# instead of AMD's official ROCm image.
FROM ubuntu:22.04
LABEL description="Folding@home AMD ROCm Container for Bastet"

ARG ROCM_RELEASE=7.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      kmod \
      polkitd \
      python3 \
      python3-websocket \
      curl \
      gnupg \
      ca-certificates \
    # get ROCm OpenCL runtime packages
    && curl -sL https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add - \
    && printf "deb [arch=amd64] https://repo.radeon.com/rocm/apt/${ROCM_RELEASE}/ jammy main" \
        | tee /etc/apt/sources.list.d/rocm.list \
    && apt-get update && apt-get install -y --no-install-recommends \
      rocm-opencl-runtime \
      rocm-smi-lib \
      rocminfo \
    # add users and groups to properly install fah-client.deb
    && useradd -ms /bin/bash fah-client \
    && groupadd -r render \
    && usermod -aG render,video fah-client \
    && mkdir /fah \
    && chown fah-client:fah-client /fah \
    # download and verify checksum
    && curl -fsSL \
      https://download.foldingathome.org/releases/public/fah-client/debian-10-64bit/release/fah-client_8.4.9_amd64.deb \
      -o fah-client.deb \
    && echo "098f4abf7c172e543de4391e86eacd10655e67d53fd4b0ae05633e2b57f9e07c fah-client.deb" \
      | sha256sum -c --strict - \
    # install and cleanup
    && DEBIAN_FRONTEND=noninteractive dpkg --install --force-depends fah-client.deb \
    && rm -rf fah-client.deb \
    && apt-get purge --autoremove -y curl \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

ENV LD_LIBRARY_PATH=/opt/rocm/lib
ENV PATH=$PATH:/opt/rocm/bin

USER fah-client
WORKDIR "/fah"
VOLUME ["/fah"]
EXPOSE 7396

ENTRYPOINT ["fah-client"]
